'use strict';
const Sequelize = require('sequelize');

module.exports = (sequelize) => {
  class Course extends Sequelize.Courses {}
  Courses.init({
    id: {
      types: Sequelize.INTEGER,
      primaryKey: true,
      autoGenerated: true,
    },
    userId: {
      type: Sequelize.INTEGER,  
    },
    description: {
      type: Sequelize.TEXT,
      allowNull: false,
      validate: {
        notEmpty: {
          msg: "Please enter a description",
         }
       }
    },
    estimatedTime: {
      type: Sequelize.STRING, 
      allowNull: true,
    },
    materialsNeeded: {
      type: Sequelize.STRING,
      allowNull: true,
    }
  },
 
  { sequelize });

  Courses.associate = (models) => {
    Courses.hasMany(models.User);              // TODO Add associations.
    
  };

  return Courses;
};


// 'use strict';
// module.exports = (sequelize, Datatypes) => {
//   const Courses = sequelize.define('Courses', {
//     id: Datatypes.INTEGER,
//     userId:Datatypes.STRING,
//     title: Datatypes.STRING,
//     description: Datatypes.STRING,
//     estimatedTime: Datatypes.STRING,
//     materialsNeeded: Datatypes.STRING
//   }, {});
//   Courses.associate = function(models) {
//     // associations can be defined here
//   };
//   return Courses;
// };