'use strict';
const Sequelize = require('sequelize');

module.exports = (sequelize) => {
  class User extends Sequelize.User {}
  User.init({
    id: {
      DataTypes: Sequelize.INTEGER,
      primaryKey: true,
      autoGenerated: true,
    },
    firstName: {
      DataTypes: Sequelize.STRING,
      allowNull: false,
      validate: {
        notEmpty: {
          msg: "Please enter a firstName",      
         }
        }
      },
    lastName: {
      DataTypes: Sequelize.STRING,
      allowNull: false,
      validate: {
        notEmpty: {
          msg: "Please enter a lastName",      
        }
      } 
    },
    emailAddress: {
      DataTypes: Sequelize.STRING,
      allowNull: false,
      validate: {
        notEmpty: {
          msg: "Please enter emailAddress",      
        }
      } 
    },  
    password: {
      DataTypes: Sequelize.STRING,
      allowNull: false,
      validate: {
        notEmpty: {
          msg: "Please enter a password",
        }
      }
    },
  },
      { sequelize });
    
      User.associate = (models) => {
        User.hasMany(models.Courses);           // TODO Add associations.
      };
    
      return User;
    };


// 'use strict';
// module.exports = (sequelize, DataTypes) => {
//   const User = sequelize.define('User', {
//     id: DataTypes.INTEGER,
//     firstName: DataTypes.STRING,
//     lastName: DataTypes.STRING,
//     emailAddress: DataTypes.STRING,
//     password: DataTypes.STRING
//   }, {});
//   User.associate = function(models) {
//     // associations can be defined here
//   };
//   return User;
// };