'use strict';
const Sequelize = require('sequelize');

module.exports = (sequelize) => {
  class Users extends Sequelize.Users {}
  Users.init({
    id: {
      DataTypes: Sequelize.INTEGER,
      primaryKey: true,
      autoGenerated: true,
    },
    firstName: {
      DataTypes: Sequelize.STRING,
      allowNull: false,
      validate: {
        notEmpty: {
          msg: "Please enter a firstName",      
         }
        }
      },
    lastName: {
      DataTypes: Sequelize.STRING,
      allowNull: false,
      validate: {
        notEmpty: {
          msg: "Please enter a lastName",      
        }
      } 
    },
    emailAddress: {
      DataTypes: Sequelize.STRING,
      allowNull: false,
      validate: {
        notEmpty: {
          msg: "Please enter emailAddress",      
        }
      } 
    },  
    password: {
      DataTypes: Sequelize.STRING,
      allowNull: false,
      validate: {
        notEmpty: {
          msg: "Please enter a password",
        }
      }
    },
  },
      { sequelize });
    
      Users.associate = (models) => {
        Users.belongsTo(models.Courses);           // TODO Add associations.
      };
    
      return Users;
    };


// 'use strict';
// module.exports = (sequelize, DataTypes) => {
//   const Users = sequelize.define('Users', {
//     id: DataTypes.INTEGER,
//     firstName: DataTypes.STRING,
//     lastName: DataTypes.STRING,
//     emailAddress: DataTypes.STRING,
//     password: DataTypes.STRING
//   }, {});
//   Users.associate = function(models) {
//     // associations can be defined here
//   };
//   return Users;
// };